
# hop
MODE_ONE_HOP = 0
MODE_TWO_HOP = 1

# algorithm
ALGORITHM_DRX = 0
ALGORITHM_LBPS_AGGR = 1
ALGORITHM_LBPS_SPLIT = 2
ALGORITHM_LBPS_MERGE = 3
ALGORITHM_LBPS_TOPDOWN = 4
ALGORITHM_LBPS_MINCYCLE = 5
ALGORITHM_LBPS_MERGECYCLE = 6

# mapping
MAPPING_M1 = 0
MAPPING_M2 = 1
MAPPING_M3 = 2
MAPPING_INTEGRATED = 3